# Generated by Django 3.1.3 on 2020-12-11 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('checklist', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorchecklistcategory',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor'),
        ),
        migrations.AddField(
            model_name='note',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_note', to='checklist.checklistcategory'),
        ),
        migrations.AddField(
            model_name='checklistcategory',
            name='checklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='checklist.checklist'),
        ),
        migrations.AddField(
            model_name='checklistcategory',
            name='vendors',
            field=models.ManyToManyField(blank=True, through='checklist.VendorChecklistCategory', to='vendors.Vendor'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='collaborators',
            field=models.ManyToManyField(blank=True, to='customers.Customer'),
        ),
    ]
