# Generated by Django 3.1.3 on 2020-12-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='checklist_collaborators',
            field=models.ManyToManyField(blank=True, null=True, related_name='checklist_collaborators', through='checklist.Collaborators', to='customers.Customer'),
        ),
    ]
