# Generated by Django 3.1.3 on 2020-12-04 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0002_auto_20201204_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='checklist',
        ),
        migrations.AddField(
            model_name='note',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category_note', to='checklist.checklistcategory'),
            preserve_default=False,
        ),
    ]
