# Generated by Django 3.1.3 on 2020-12-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('checklist', '0003_auto_20201204_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='checklist_collaborators',
        ),
        migrations.AddField(
            model_name='checklist',
            name='collaborators',
            field=models.ManyToManyField(blank=True, null=True, to='customers.Customer'),
        ),
        migrations.DeleteModel(
            name='Collaborators',
        ),
    ]
