# Generated by Django 3.1.3 on 2020-12-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('checklist', '0004_auto_20201206_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='collaborators',
            field=models.ManyToManyField(blank=True, to='customers.Customer'),
        ),
    ]
