# Generated by Django 3.1.3 on 2020-12-08 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_delete_categories'),
        ('checklist', '0005_auto_20201206_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorChecklistCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=300, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist.checklistcategory')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor')),
            ],
        ),
        migrations.DeleteModel(
            name='VendorCheckCategory',
        ),
        migrations.AddField(
            model_name='checklistcategory',
            name='vendors',
            field=models.ManyToManyField(blank=True, through='checklist.VendorChecklistCategory', to='vendors.Vendor'),
        ),
    ]
