# Generated by Django 3.1.3 on 2020-11-29 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user')),
                ('vendor_name', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='logo')),
                ('cover_image', models.ImageField(upload_to='cover_image')),
                ('about', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VendorImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vendor_media')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vendors.vendor')),
            ],
        ),
    ]
