# Generated by Django 3.1.3 on 2020-12-09 12:03

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=150)),
                ('tag_type', models.CharField(choices=[('Location', 'Location'), ('Culture', 'Culture')], default='Culture', max_length=10)),
            ],
            options={
                'ordering': ['tag_name'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user')),
                ('vendor_name', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='logo')),
                ('cover_image', models.ImageField(upload_to='cover_image')),
                ('slug', models.SlugField(default='')),
                ('about', ckeditor.fields.RichTextField(blank=True, default='', null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='vendors.category')),
            ],
        ),
        migrations.CreateModel(
            name='VendorTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to='vendors.tag')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_tags', to='vendors.vendor')),
            ],
            options={
                'unique_together': {('vendor', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='VendorImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vendor_images')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vendors.vendor')),
            ],
        ),
        migrations.AddField(
            model_name='tag',
            name='vendors',
            field=models.ManyToManyField(related_name='vendor_tag', through='vendors.VendorTag', to='vendors.Vendor'),
        ),
    ]
