# Generated by Django 3.1.3 on 2020-12-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_pic',
            field=models.ImageField(blank=True, upload_to='category_pic'),
        ),
    ]
