# Generated by Django 3.1.3 on 2021-01-05 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_vendor_review_int'),
        ('vendors', '0002_auto_20201230_1644'),
    ]

    operations = [
    ]
