# Generated by Django 3.1.3 on 2020-12-04 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_categories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
