# Generated by Django 3.1.3 on 2020-12-03 15:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_auto_20201129_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='about',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True),
        ),
    ]
