# Generated by Django 3.1.3 on 2020-12-02 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_auto_20201202_1323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={},
        ),
        migrations.RemoveField(
            model_name='tag',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='tag_name',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='vendors',
        ),
        migrations.AlterUniqueTogether(
            name='vendortag',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='vendortag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='vendortag',
            name='vendor',
        ),
    ]
