# Generated by Django 3.1.3 on 2020-12-02 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_auto_20201202_1343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['tag_name']},
        ),
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.TextField(default='hello', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(default='hi', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='vendors',
            field=models.ManyToManyField(related_name='vendor_tag', through='vendors.VendorTag', to='vendors.Vendor'),
        ),
        migrations.AddField(
            model_name='vendortag',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to='vendors.tag'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendortag',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_tags', to='vendors.vendor'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='vendortag',
            unique_together={('vendor', 'tag')},
        ),
    ]
