# Generated by Django 3.1.3 on 2020-12-02 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_auto_20201202_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='vendors.category'),
        ),
    ]
