# Generated by Django 3.1.3 on 2020-12-02 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_auto_20201202_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='vendors',
            new_name='vendor_tag',
        ),
    ]
