# Generated by Django 3.1.3 on 2020-12-02 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0007_auto_20201202_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='vendor_tag',
            new_name='vendors',
        ),
    ]
