# Generated by Django 3.1.3 on 2020-12-01 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='desciption',
            new_name='description',
        ),
    ]
