# Generated by Django 3.1.3 on 2020-12-03 09:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20201201_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True),
        ),
    ]
