# Generated by Django 3.1.3 on 2020-11-29 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='culture',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Brahmin'), (2, 'Newar'), (3, 'Tharu'), (4, 'Terai')], null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='location',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Kathmandu'), (2, 'Pokhara'), (3, 'Chitwan'), (4, 'Janakpur'), (5, 'Dang')], null=True),
        ),
    ]
